modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="warriorcats_events"
displayName="Warrior Cats Events"
description="Turn your world into a Warrior Cats survival experience!"
version="1.0.2"
authors="Klyonstar / Snowstar"
credits="""
Sharon Hurvitz (Author of "Generations")
Bookwom, Telefonjoker, Cat,
Whale_shark, Sejr
"""
logoFile="banner.png"
logoBlur=false
displayTest="IGNORE_SERVER_VERSION"
updateJSONURL=""
displayURL="https://www.curseforge.com/minecraft/mc-mods/warriorcats-events"
license= "All Rights Reserved"

[[dependencies.warriorcats_events]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.warriorcats_events]]
    modId="geckolib"
    mandatory=true
    versionRange="[4.8.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.warriorcats_events]]
    modId="walkers"
    mandatory=true
    versionRange="[5.7,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.warriorcats_events]]
    modId="craftedcore"
    mandatory=true
    versionRange="[5.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.warriorcats_events]]
    modId="patchouli"
    mandatory=true
    versionRange="[1.20.1-84,)"
    ordering="NONE"
    side="BOTH"


