modLoader="javafml"
loaderVersion="[47,)" 
license="All Rights Reserved"

[[mods]]
modId="warriorcats_events"          
version="1.0.0"
displayName="WarriorCats Events"    
authors="Mapple"
description="Simple WarriorCats event sequences."

displayTest="IGNORE_SERVER_VERSION"
updateJSONURL=""
displayURL=""

[[dependencies.warriorcats_events]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"


