modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="warriorcats_events"
displayName="WarriorCats Events (Tester's Beta)"
description="Turn your world into a Warrior Cats survival experience!"
version="3.1.0 beta"
authors="Snow / Maple"
credits="Soon..."
logoFile="banner.png"
logoBlur=false
displayTest="IGNORE_SERVER_VERSION"
updateJSONURL=""
displayURL="https://www.curseforge.com/servers/minecraft"
license= "All Rights Reserved"

[[dependencies.warriorcats_events]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.geckolib]]
modId="geckolib"
mandatory=true
versionRange="[4.8.2,)"
ordering="NONE"
side="BOTH"

[[dependencies.walkers]]
modId="walkers"
mandatory=true
versionRange="[5.7,)"
ordering="NONE"
side="BOTH"

[[dependencies.craftedcore]]
modId="craftedcore"
mandatory=true
versionRange="[5.8,)"
ordering="NONE"
side="BOTH"


